import path from "path"
import fs from "fs"
import { saveFile } from "./utils.js"
import { generateBlockTextureJson, generateItemTextureJson } from "./tools/textureSet.js"
//import { FlipbookTextures, ItemTextureManager, TerrainTextureManager } from "../core/texture.js"
import { GRegistryServer } from "./registryServer.js"

// ── 生成物清单：用于精确清理「陈旧产物」（缺口 9）──
// 只有**框架自己生成过**的文件才会被清理；用户 res/ 拷进来的文件与手写文件一律不碰。
const MANIFEST_VERSION = 1
const manifestPathOf = (buildPath, projectName) =>
    path.join(buildPath, `.sapdon_generated_${projectName}.json`)

function readManifest(buildPath, projectName) {
    const p = manifestPathOf(buildPath, projectName)
    try {
        const parsed = JSON.parse(fs.readFileSync(p, 'utf-8'))
        if (parsed && parsed.v === MANIFEST_VERSION && Array.isArray(parsed.files)) return { files: parsed.files, existed: true }
    } catch { /* 首次构建没有清单，属正常 */ }
    return { files: [], existed: false }
}

/**
 * 清掉历史版本留在**行为包**里的 `blocks.json`。
 *
 * `blocks.json` 规范上属资源包（RP 根目录），但 05bd104..本次修复之间框架把它写在 BP，
 * 那些文件**不在任何清单里**（当年还没有清单机制），只能在这里显式点名清理
 * —— 否则「dev/*_BP/blocks.json 不存在」这条验收永远过不了。
 *
 * ⚠️ 每次都查而不是只在「没有清单的首次构建」做：清单是否存在取决于构建历史
 *    （中断的构建也会留下清单），按清单判断会漏掉这类残留。规则本身是**一个确切路径**，
 *    不做任何目录扫描，所以无条件执行也是安全的。
 */
function cleanLegacyBpBlocksJson(buildPath, projectName) {
    const rel = `${projectName}_BP/blocks.json`
    const abs = path.join(buildPath, rel)
    if (fs.existsSync(abs)) {
        fs.rmSync(abs, { force: true })
        console.log(`已删除历史误放产物 ${rel}（blocks.json 规范属资源包 RP，框架不会再往 BP 写）`)
    }
}

function writeManifest(buildPath, projectName, files) {
    saveFile(manifestPathOf(buildPath, projectName), JSON.stringify({
        v: MANIFEST_VERSION,
        note: 'sapdon 生成物清单：本次构建写出的产物文件（相对 dev/ 的路径）。下次构建据此删除不再生成的旧文件。请勿手工编辑。',
        files: [...files].sort(),
    }, null, 2))
}

/**
 * 删除上一次构建生成、但本次不再生成的产物（改名/删条目的场景）。
 * ⚠️ 只删清单里记过的路径 —— 不扫目录、不猜规则，避免误删用户 res/ 资源与手写文件。
 */
function cleanStaleGenerated(buildPath, previousFiles, nextFiles) {
    const next = new Set(nextFiles)
    let removed = 0
    for (const rel of previousFiles) {
        if (next.has(rel)) continue
        const abs = path.join(buildPath, rel)
        if (fs.existsSync(abs)) {
            fs.rmSync(abs, { force: true })
            removed++
            console.log(`已清理陈旧产物: ${rel}`)
        }
    }
    return removed
}

/**
 * 写入/更新自定义组件注册索引（缺口 10/11）。
 *
 * 把文件里**所有**「框架生成段」都摘掉（可能同时存在旧版段与本函数的标记块，
 * 例如旧版留下 `// Auto-generated by sapdon.` 段、新逻辑又追加了标记块），
 * 剩下的**全是用户/模板内容**，然后在第一个生成段的位置放回唯一的标记块。
 *
 * - 无生成段（ts 模板占位注释、js 模板的 registry 调用、用户手写）→ **追加**，绝不覆盖
 * - 幂等：连跑两次结果完全一致
 *
 * ⚠️ 生成块里用 `import { system as __sapdon_system }` 而不是裸 `system`：
 *    追加场景下文件里可能已有 `import { system }`，同名重复声明会让整个脚本包
 *    rollup 报 `Identifier "system" has already been declared`（block_demo 实测踩到）。
 */
function findGeneratedSpans(content) {
    const spans = []
    const push = (start, end) => { if (end > start) spans.push({ start, end }) }

    const beginIdx = content.indexOf(INDEX_BEGIN)
    if (beginIdx !== -1) {
        const endIdx = content.indexOf(INDEX_END, beginIdx)
        if (endIdx > beginIdx) push(beginIdx, endIdx + INDEX_END.length)
    }

    const legacyIdx = content.indexOf(LEGACY_HEADER)
    if (legacyIdx !== -1 && !spans.some((s) => legacyIdx >= s.start && legacyIdx < s.end)) {
        const subIdx = content.indexOf('system.beforeEvents.startup.subscribe(', legacyIdx)
        let endIdx = -1
        if (subIdx !== -1) {
            const closeIdx = content.indexOf('\n});', subIdx)
            if (closeIdx !== -1) endIdx = closeIdx + '\n});'.length
        }
        push(legacyIdx, endIdx === -1 ? content.length : endIdx)
    }
    return spans.sort((a, b) => a.start - b.start)
}

function writeCustomComponentIndex(indexPath, customComponentInfos) {
    const importLines = customComponentInfos.map(({ safeName }) =>
        `import { ${safeName} } from './${safeName}.js';`
    )
    const registerLines = customComponentInfos.map(({ safeName, componentId }) =>
        `  init.blockComponentRegistry.registerCustomComponent('${componentId}', ${safeName});`
    )
    const block = [
        INDEX_BEGIN,
        `import { system as ${SYSTEM_ALIAS} } from '@minecraft/server';`,
        '',
        ...importLines,
        '',
        `${SYSTEM_ALIAS}.beforeEvents.startup.subscribe((init) => {`,
        ...registerLines,
        `});`,
        INDEX_END,
    ].join('\n')

    if (!fs.existsSync(indexPath)) {
        saveFile(indexPath, block + '\n')
        console.log(`已生成自定义组件注册索引: ${indexPath}`)
        return
    }

    const current = fs.readFileSync(indexPath, 'utf-8')
    const spans = findGeneratedSpans(current)

    if (spans.length === 0) {
        // 模板占位 / 用户手写：追加，绝不覆盖
        const sep = current.endsWith('\n') ? '' : '\n'
        saveFile(indexPath, `${current}${sep}\n${block}\n`)
        console.log(`已在既有注册索引末尾追加自动注册块（原内容保留）: ${indexPath}`)
        return
    }

    // 摘掉所有生成段，留一个槽位放回唯一标记块
    let work = ''
    let cursor = 0
    let slotPlaced = false
    for (const span of spans) {
        work += current.slice(cursor, span.start)
        if (!slotPlaced) { work += INDEX_SLOT; slotPlaced = true }
        cursor = span.end
    }
    work += current.slice(cursor)
    work = work.replace(INDEX_SLOT, block)
    // 收拾摘除留下的多余空行
    work = work.replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '')
    if (!work.endsWith('\n')) work += '\n'

    if (work === current) {
        console.log(`自定义组件注册索引已是最新，未改动: ${indexPath}`)
        return
    }
    saveFile(indexPath, work)
    console.log(`已更新自定义组件注册索引（保留手写部分，共 ${customComponentInfos.length} 个组件）: ${indexPath}`)
}

const INDEX_BEGIN = '// >>> sapdon:custom-component-registry (auto-generated, 请勿手改本块) >>>'
const INDEX_END = '// <<< sapdon:custom-component-registry <<<'
const LEGACY_HEADER = '// Auto-generated by sapdon.'
const SYSTEM_ALIAS = '__sapdon_system'
/** 临时占位符（NUL 字符不会出现在正常源码里），写文件前被替换掉 */
const INDEX_SLOT = '\u0000SAPDON_INDEX_SLOT\u0000'


/**
 * Server
 * 加载并执行模组文件
 * @param {string} modPath 模组文件路径
 * @param {string} buildPath 构建目录路径
 * @param {string} projectName 项目名
 */
export const generateAddon = async (modPath, buildPath, projectName) => {
    try {
        const buildBehDirPath = path.join(buildPath, `${projectName}_BP`)
        const buildResDirPath = path.join(buildPath, `${projectName}_RP`)
        const resDir = (...name) => path.join(buildResDirPath, ...name)

        // 上次构建的产物清单（用于本次清理陈旧产物）
        const previousFiles = readManifest(buildPath, projectName)
        // 历史误放产物（BP 里的 blocks.json）逐个点名清理
        cleanLegacyBpBlocksJson(buildPath, projectName)
        // 本次构建写出的产物（相对 buildPath）
        const generatedFiles = []
        const record = (absPath) => { generatedFiles.push(path.relative(buildPath, absPath)) }

        // 从全局注册表中获取数据
        const dataList = GRegistryServer.getDataList()

        // 初始化用户自定义纹理数据
        const textureData = {
            item: null,
            block: null,
            flipbook: []
        }

        // 用于收集自定义组件脚本信息
        const customComponentInfos = []

        // 遍历数据并分类处理
        for (const { name, root, path: dataPath, data } of dataList) {
            console.log('处理数据:', name, root, dataPath);
            
            // 处理纹理数据
            switch (name) {
                case "item_texture":
                    textureData.item = data;
                    console.log('用户物品贴图数据:', textureData.item);
                    continue;
                    
                case "terrain_texture":
                    textureData.block = data;
                    console.log('用户方块贴图数据:', textureData.block);
                    continue;
                    
                case "flipbook_textures":
                    textureData.flipbook = data;
                    console.log('用户翻书贴图数据:', textureData.flipbook);
                    continue;
            }

            // 处理自定义组件脚本文件（写入项目源码目录，由用户编辑）
            if (data._scriptSource) {
                const projectPath = path.dirname(modPath);
                const filePath = path.join(projectPath, dataPath, `${name}.js`);

                if (fs.existsSync(filePath)) {
                    console.log(`自定义组件脚本已存在，跳过: ${filePath}`);
                } else {
                    saveFile(filePath, data.source);
                    console.log(`已生成自定义组件脚本: ${filePath}`);
                }

                customComponentInfos.push({ safeName: name, componentId: data.componentId });
                continue;
            }
            
            // 处理其他类型的数据文件
            const rootPath = root === "behavior" ? `${projectName}_BP` : `${projectName}_RP`;
            const buildRootPath = path.join(buildPath, rootPath);
            const filePath = path.join(buildRootPath, dataPath, `${name}.json`);
            
            // 保存文件
            saveFile(filePath, JSON.stringify(data, null, 2));
            record(filePath);
        }

        // 生成自定义组件注册索引文件（写入项目源码目录）
        if (customComponentInfos.length > 0) {
            const projectPath = path.dirname(modPath);
            const scriptsDir = path.join(projectPath, 'scripts', 'custom_components');
            const indexPath = path.join(scriptsDir, 'index.js');

            // ⚠️ 必须是「合并/追加」而不是 existsSync 就跳过：
            //    索引文件在 ts 模板里是**预置占位文件**（且被 scripts/index.ts import），
            //    「存在即跳过」会让注册索引**永远不更新** —— 新增组件进不去、旧组件留在里面。
            writeCustomComponentIndex(indexPath, customComponentInfos);
        }

        // 生成纹理 JSON 文件
        await generateTextureFiles(resDir, projectName, textureData, record);

        // 清理陈旧产物（缺口 9）：上一次生成、这次不再生成的旧 JSON
        cleanStaleGenerated(buildPath, previousFiles.files, generatedFiles);
        // 写回本次产物清单
        writeManifest(buildPath, projectName, generatedFiles);

        console.log(`已加载并执行 ${modPath} 文件！`);
    } catch (err) {
        console.error(`加载或执行 ${modPath} 失败：${err.message}`);
        console.error(err.stack);
    }
};

/**
 * 生成纹理相关的 JSON 文件
 * @param {(...name: string[]) => string} resDir RP 目录拼接
 * @param {(absPath: string) => void} [record] 记录产物路径（用于陈旧产物清理）
 */
async function generateTextureFiles(resDir, projectName, textureData, record = () => {}) {
    // 生成 item_texture.json
    const itemTextureDir = resDir("textures/items");
    const itemTextureJsonPath = resDir("textures/item_texture.json");
    await generateItemTextureJson(itemTextureDir, itemTextureJsonPath, projectName, textureData.item);
    record(itemTextureJsonPath);
    
    // 生成 terrain_texture.json
    const terrainTextureDir = resDir("textures/blocks");
    const terrainTextureJsonPath = resDir("textures/terrain_texture.json");
    await generateBlockTextureJson(terrainTextureDir, terrainTextureJsonPath, projectName, textureData.block);
    record(terrainTextureJsonPath);
    
    // 生成 flipbook_textures.json
    const flipbookTexturesPath = resDir("textures/flipbook_textures.json");
    saveFile(flipbookTexturesPath, JSON.stringify(textureData.flipbook, null, 2));
    record(flipbookTexturesPath);
    //console.log('翻书贴图 JSON 文件生成成功。');
}