// Auto-generated by sapdon. Edit to implement your component.
import { world } from '@minecraft/server';

const blockdemo_tick_update = {
  onTick({ block }) {
    const key = `blockdemo:ticking_ticks:${block.location.x},${block.location.y},${block.location.z}`;
    const ticks = (world.getDynamicProperty(key) ?? 0) + 1;
    world.setDynamicProperty(key, ticks);
    if (ticks % 100 === 0) {
      world.sendMessage(`Ticking block at ${block.location} ticked ${ticks} times`);
    }
  },
};

export { blockdemo_tick_update };