// Auto-generated by sapdon. Edit to implement your component.
import { world } from '@minecraft/server';

const blockdemo_head_rotate = {
  onPlayerInteract({ block, dimension, face, faceLocation, player }) {
    // TODO: implement
  },
  onTick({ block, dimension }) {
    // TODO: implement
  },
};

export { blockdemo_head_rotate };