// Auto-generated by sapdon. Edit to implement your component.
import { world } from '@minecraft/server';

const blockdemo_tick_update = {
  onTick({ block, dimension }) {
    const ticks = (dimension.getDynamicProperty('blockdemo:ticking_ticks') ?? 0) + 1;
    dimension.setDynamicProperty('blockdemo:ticking_ticks', ticks);
    if (ticks % 100 === 0) {
      world.sendMessage(`Ticking block at ${block.location} ticked ${ticks} times`);
    }
  },
};

export { blockdemo_tick_update };