// Auto-generated by sapdon.
import { system } from '@minecraft/server';

import { blockdemo_head_rotate } from './blockdemo_head_rotate.js';

system.beforeEvents.startup.subscribe((init) => {
  init.blockComponentRegistry.registerCustomComponent('blockdemo:head_rotate', blockdemo_head_rotate);
});
